# Generated by Django 5.0 on 2026-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tax_taxdeduction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="tax_documents/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tax_taxdocument",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_year", models.IntegerField()),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married_filing_jointly", "Married Filing Jointly"),
                            ("married_filing_separately", "Married Filing Separately"),
                            ("head_of_household", "Head of Household"),
                            ("qualifying_widow", "Qualifying Widow(er)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("filed", "Filed"),
                            ("accepted", "Accepted"),
                            ("audit", "Under Audit"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "gross_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "taxable_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("filing_date", models.DateField(blank=True, null=True)),
                ("acceptance_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tax_taxreturn",
                "ordering": ["-tax_year", "-created_at"],
            },
        ),
    ]
