import { useState, useEffect } from 'react'

interface Report {
  id: string
  title: string
  type: string
  createdAt: string
  generatedBy: string
  status: string
}

export default function Reports() {
  const [reports, setReports] = useState<Report[]>([])
  const [loading, setLoading] = useState(true)
  const [filterType, setFilterType] = useState('all')

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const response = await fetch('/api/v1/reports/reports/', {
          headers: {
            Authorization: `Bearer ${localStorage.getItem('access_token')}`,
          },
        })
        const data = await response.json()
        setReports(data.results || data)
      } catch (error) {
        console.error('Error fetching reports:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchReports()
  }, [])

  const filteredReports =
    filterType === 'all' ? reports : reports.filter((r) => r.type === filterType)

  if (loading) {
    return <div className="p-8">Loading reports...</div>
  }

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold">Reports & Analytics</h1>
        <button className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
          Generate New Report
        </button>
      </div>

      <div className="mb-6 flex gap-4">
        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
          className="border rounded px-4 py-2"
        >
          <option value="all">All Reports</option>
          <option value="financial">Financial</option>
          <option value="tax">Tax</option>
          <option value="investment">Investment</option>
          <option value="client">Client</option>
        </select>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full border-collapse">
          <thead className="bg-gray-100">
            <tr>
              <th className="border p-4 text-left font-semibold">Title</th>
              <th className="border p-4 text-left font-semibold">Type</th>
              <th className="border p-4 text-left font-semibold">Generated By</th>
              <th className="border p-4 text-left font-semibold">Date</th>
              <th className="border p-4 text-left font-semibold">Status</th>
              <th className="border p-4 text-left font-semibold">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.length === 0 ? (
              <tr>
                <td colSpan={6} className="border p-4 text-center text-gray-500">
                  No reports found
                </td>
              </tr>
            ) : (
              filteredReports.map((report) => (
                <tr key={report.id} className="hover:bg-gray-50">
                  <td className="border p-4">{report.title}</td>
                  <td className="border p-4">
                    <span className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm">
                      {report.type}
                    </span>
                  </td>
                  <td className="border p-4">{report.generatedBy}</td>
                  <td className="border p-4">
                    {new Date(report.createdAt).toLocaleDateString()}
                  </td>
                  <td className="border p-4">
                    <span
                      className={`px-3 py-1 rounded-full text-sm ${
                        report.status === 'completed'
                          ? 'bg-green-100 text-green-800'
                          : report.status === 'processing'
                            ? 'bg-yellow-100 text-yellow-800'
                            : 'bg-gray-100 text-gray-800'
                      }`}
                    >
                      {report.status}
                    </span>
                  </td>
                  <td className="border p-4 flex gap-2">
                    <button className="text-blue-600 hover:underline">View</button>
                    <button className="text-gray-600 hover:underline">Download</button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
