# Generated by Django 5.0 on 2026-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("bond", "Bond"),
                            ("mutual_fund", "Mutual Fund"),
                            ("etf", "ETF"),
                            ("real_estate", "Real Estate"),
                            ("crypto", "Cryptocurrency"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("purchase_date", models.DateField()),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "gain_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "gain_loss_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investments_investment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benchmark_name", models.CharField(max_length=100)),
                (
                    "benchmark_return",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "benchmark_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investments_investmentbenchmark",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_return",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_return_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investments_portfolio",
            },
        ),
    ]
