# Generated by Django 5.0 on 2026-02-19 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("investments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investmentbenchmark",
            name="portfolio",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benchmark",
                to="investments.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="investments.portfolio",
            ),
        ),
    ]
